### PR TITLE
7 http server setup

### PR DESCRIPTION
**Pull request by Mateusz-Dobrzynski**

### CODE REVIEW

**Review by hubertborysowski — COMMENTED** [review]
Everything works fine but things here differ from the AC on Trello.
I have not found `An endpoint (e.g. 127.0.0.1:8080 on a local device) is exposed on a host device;
It is possible to send HTTP requests via Postman and receive responses`, so I am not sure whether should I approve this, or not.

**Comment by Mateusz-Dobrzynski** [comment]
You can check that with `curl http://localhost:8080` or by typing `127.0.0.1:8080` in your browser (you should see a blank page)

**Comment by hubertborysowski** [comment]
> You can check that with `curl http://localhost:8080` or by typing `127.0.0.1:8080` in your browser (you should see a blank page)

So I get this: 
2023-06-29 12_14_21-127 0 0 1_8080 - Opera
If that is what I should get then it is all fine.
Curl says the same.

**Comment by Mateusz-Dobrzynski** [comment]
Yes, that's it. It indicates that the server is working but there is nothing useful implemented yet, hence the 404.

**Review by hubertborysowski — APPROVED** [review]
Approved. Everything is fine and understandable.

**Pull request merged**
